import type { EntityImportConfig } from "@/lib/import/types";

// Mirrors the original components/leads/LeadImportModal.tsx column map + template
// so behaviour is unchanged after the modal delegates to the shared ImportPanel.
export const leadImportConfig: EntityImportConfig = {
  entity: "lead",
  label: "Leads",
  endpoint: "/api/leads/import",
  columnMap: {
    "full name": "full_name",
    "name": "full_name",
    "full_name": "full_name",
    "phone": "phone",
    "mobile": "phone",
    "phone number": "phone",
    "contact": "phone",
    "lead source": "lead_source",
    "source": "lead_source",
    "lead_source": "lead_source",
    "property type": "property_type",
    "property_type": "property_type",
    "type": "property_type",
    "purpose": "purpose",
    "potential lead value": "potential_lead_value",
    "pipeline value": "potential_lead_value",
    "potential_lead_value": "potential_lead_value",
    "lead value": "potential_lead_value",
    "email": "email",
    "email address": "email",
    "whatsapp": "whatsapp",
    "whatsapp number": "whatsapp",
    "temperature": "temperature",
    "priority": "temperature",
    "budget min": "budget_min",
    "budget_min": "budget_min",
    "min budget": "budget_min",
    "budget max": "budget_max",
    "budget_max": "budget_max",
    "max budget": "budget_max",
    "unit type": "unit_type",
    "unit_type": "unit_type",
    "configuration": "unit_type",
    "location preference": "location_preference",
    "location_preference": "location_preference",
    "location": "location_preference",
    "preferred location": "location_preference",
    "timeline to buy": "timeline_to_buy",
    "timeline_to_buy": "timeline_to_buy",
    "timeline": "timeline_to_buy",
    "campaign source": "campaign_source",
    "campaign_source": "campaign_source",
    "campaign": "campaign_source",
    "referral source": "referral_source",
    "referral_source": "referral_source",
    "referral": "referral_source",
    "referred by": "referral_source",
    "reason": "reason_for_interest",
    "reason for interest": "reason_for_interest",
    "reason_for_interest": "reason_for_interest",
    "notes": "notes",
    "note": "notes",
    "remarks": "notes",
    "lead type": "lead_type",
    "lead_type": "lead_type",
    "type of lead": "lead_type",
    "client type": "lead_type",
  },
  mandatory: ["full_name", "phone", "lead_source", "lead_type", "property_type", "purpose", "potential_lead_value"],
  mandatoryLabels: {
    full_name: "Full Name",
    phone: "Phone",
    lead_source: "Lead Source",
    lead_type: "Lead Type",
    property_type: "Property Type",
    purpose: "Purpose",
    potential_lead_value: "Potential Lead Value",
  },
  templateColumns: [
    { header: "Full Name*", note: "Min 2 chars", sample: "Rajesh Kumar" },
    { header: "Phone*", note: "Min 7 digits", sample: "9876543210" },
    { header: "Lead Source*", note: "e.g. Website, Facebook, Referral", sample: "Facebook" },
    { header: "Lead Type*", note: "EndUser | Broker | ChannelPartner | Others", sample: "EndUser" },
    { header: "Property Type*", note: "Residential | Commercial | Plot | Villa | Apartment | Office", sample: "Apartment" },
    { header: "Purpose*", note: "EndUse | Investment", sample: "EndUse" },
    { header: "Potential Lead Value*", note: "Numeric (e.g. 5000000)", sample: "7500000" },
    { header: "Email", note: "Optional", sample: "rajesh@example.com" },
    { header: "WhatsApp", note: "Optional", sample: "9876543210" },
    { header: "Temperature", note: "Hot | Warm | Cold | FollowUpLater (default: Cold)", sample: "Warm" },
    { header: "Budget Min", note: "Optional numeric", sample: "6000000" },
    { header: "Budget Max", note: "Optional numeric", sample: "9000000" },
    { header: "Unit Type", note: "e.g. 2BHK", sample: "2BHK" },
    { header: "Location Preference", note: "e.g. Whitefield", sample: "Koramangala" },
    { header: "Timeline to Buy", note: "e.g. 3 months", sample: "6 months" },
    { header: "Campaign Source", note: "Optional", sample: "Summer Campaign" },
    { header: "Referral Source", note: "Optional", sample: "" },
    { header: "Notes", note: "Optional", sample: "Looking for ready to move" },
  ],
  templateFileName: "leads_import_template.xlsx",
  previewColumns: [
    { field: "full_name", label: "Full Name", required: true },
    { field: "phone", label: "Phone", required: true },
    { field: "lead_source", label: "Lead Source", required: true },
    { field: "lead_type", label: "Lead Type", required: true },
    { field: "property_type", label: "Property Type", required: true },
    { field: "purpose", label: "Purpose", required: true },
    { field: "potential_lead_value", label: "Potential Value", required: true },
    { field: "email", label: "Email" },
    { field: "temperature", label: "Temp" },
  ],
  enumHints: [
    { label: "Lead Type", values: "EndUser · Broker · ChannelPartner · Others" },
    { label: "Property Type", values: "Residential · Commercial · Plot · Villa · Apartment · Office" },
    { label: "Purpose", values: "EndUse · Investment" },
    { label: "Temperature", values: "Hot · Warm · Cold · FollowUpLater (defaults to Cold if blank)" },
  ],
  helpText: "All imported leads are assigned to you and can be reassigned after import.",
};
