import type { EntityImportConfig } from "@/lib/import/types";

// Flat opportunity import. Multi-row configurations aren't expressible in a flat
// sheet, so a single minimal configuration is synthesized from units/price_per_unit
// (see app/api/opportunities/import/route.ts). Leave both blank to create a
// placeholder opportunity to finish in the form.
export const opportunityImportConfig: EntityImportConfig = {
  entity: "opportunity",
  label: "Opportunities",
  endpoint: "/api/opportunities/import",
  columnMap: {
    "name": "name",
    "opportunity": "name",
    "opportunity name": "name",
    "project": "project",
    "project name": "project",
    "developer": "developer",
    "seller": "developer",
    "developer / seller": "developer",
    "opportunity by": "opportunity_by",
    "opportunity_by": "opportunity_by",
    "opp by": "opportunity_by",
    "property type": "property_type",
    "property_type": "property_type",
    "type": "property_type",
    "location": "location",
    "commission": "commission_percent",
    "commission %": "commission_percent",
    "commission percent": "commission_percent",
    "commission_percent": "commission_percent",
    "status": "status",
    "notes": "notes",
    "remarks": "notes",
    "units": "units",
    "number of units": "units",
    "no of units": "units",
    "price per unit": "price_per_unit",
    "price_per_unit": "price_per_unit",
    "unit price": "price_per_unit",
  },
  mandatory: ["name", "project", "property_type", "location", "commission_percent"],
  mandatoryLabels: {
    name: "Name",
    project: "Project",
    property_type: "Property Type",
    location: "Location",
    commission_percent: "Commission %",
  },
  templateColumns: [
    { header: "Name*", note: "Opportunity name", sample: "Nitya Infra" },
    { header: "Project*", note: "Project name", sample: "Sunshine" },
    { header: "Property Type*", note: "Residential | Commercial | Plot | Villa | Apartment | Office | Land", sample: "Apartment" },
    { header: "Location*", note: "e.g. Whitefield", sample: "Kalyan Nagar" },
    { header: "Commission %*", note: "Numeric 0–100 (e.g. 2)", sample: "2" },
    { header: "Opportunity By", note: "Developer | Seller | Buyer (default: Developer)", sample: "Developer" },
    { header: "Status", note: "Active | Inactive | Sold (default: Active)", sample: "Active" },
    { header: "Developer", note: "Optional (developer/seller name)", sample: "Alef Homes" },
    { header: "Units", note: "Optional numeric — synthesizes one configuration", sample: "50" },
    { header: "Price Per Unit", note: "Optional numeric — with Units drives sales value", sample: "8000000" },
    { header: "Notes", note: "Optional", sample: "" },
  ],
  templateFileName: "opportunities_import_template.xlsx",
  previewColumns: [
    { field: "name", label: "Name", required: true },
    { field: "project", label: "Project", required: true },
    { field: "property_type", label: "Property Type", required: true },
    { field: "location", label: "Location", required: true },
    { field: "commission_percent", label: "Commission %", required: true },
    { field: "units", label: "Units" },
    { field: "price_per_unit", label: "Price/Unit" },
  ],
  enumHints: [
    { label: "Property Type", values: "Residential · Commercial · Plot · Villa · Apartment · Office · Land" },
    { label: "Opportunity By", values: "Developer · Seller · Buyer (defaults to Developer)" },
    { label: "Status", values: "Active · Inactive · Sold (defaults to Active)" },
  ],
  helpText: "Provide Units + Price Per Unit to auto-compute sales value; otherwise a placeholder configuration is created to finish in the form.",
};
