import type { EntityImportConfig } from "@/lib/import/types";

// Flat task import. assigned_to is resolved by name (defaults to the importer);
// lead/opportunity/client are optionally linked by their number/name.
export const taskImportConfig: EntityImportConfig = {
  entity: "task",
  label: "Tasks",
  endpoint: "/api/tasks/import",
  columnMap: {
    "title": "title",
    "task": "title",
    "task title": "title",
    "description": "description",
    "priority": "priority",
    "due date": "due_date",
    "due_date": "due_date",
    "due": "due_date",
    "start date": "start_date",
    "start_date": "start_date",
    "assigned to": "assigned_to",
    "assignee": "assigned_to",
    "assigned_to": "assigned_to",
    "sector": "sector",
    "lead number": "lead_number",
    "lead_number": "lead_number",
    "lead id": "lead_number",
    "opportunity number": "opp_number",
    "opp number": "opp_number",
    "opp_number": "opp_number",
    "opportunity id": "opp_number",
    "client": "client_name",
    "client name": "client_name",
    "client_name": "client_name",
    "revenue amount": "revenue_amount",
    "revenue_amount": "revenue_amount",
    "notes": "notes",
    "remarks": "notes",
  },
  mandatory: ["title", "due_date"],
  mandatoryLabels: {
    title: "Title",
    due_date: "Due Date",
  },
  templateColumns: [
    { header: "Title*", note: "Min 3 chars", sample: "Call back client" },
    { header: "Due Date*", note: "YYYY-MM-DD or DD/MM/YYYY", sample: "2026-09-20" },
    { header: "Priority", note: "Low | Medium | High | Critical (default: Medium)", sample: "High" },
    { header: "Assigned To", note: "User name (defaults to you if blank/unmatched-error)", sample: "Revathi" },
    { header: "Start Date", note: "Optional; YYYY-MM-DD", sample: "" },
    { header: "Sector", note: "Optional", sample: "Residential" },
    { header: "Lead Number", note: "Optional; e.g. DS-LEAD-001769", sample: "" },
    { header: "Opp Number", note: "Optional; e.g. DS-OPP-000017", sample: "" },
    { header: "Client Name", note: "Optional; existing client name", sample: "" },
    { header: "Revenue Amount", note: "Optional numeric", sample: "" },
    { header: "Notes", note: "Optional", sample: "" },
  ],
  templateFileName: "tasks_import_template.xlsx",
  previewColumns: [
    { field: "title", label: "Title", required: true },
    { field: "due_date", label: "Due Date", required: true },
    { field: "priority", label: "Priority" },
    { field: "assigned_to", label: "Assigned To" },
    { field: "lead_number", label: "Lead" },
    { field: "opp_number", label: "Opportunity" },
  ],
  enumHints: [
    { label: "Priority", values: "Low · Medium · High · Critical (defaults to Medium)" },
  ],
  helpText: "Tasks with an unmatched Assigned To name fail that row; blank Assigned To defaults to you.",
};
